### ISSUE TITLE
Looking for help with this repo?

### ISSUE THREAD

**Issue by jonfujita** [mangalam-research/btw#25]
@lddubeau Looking for help? I'm trying to get started with contributing to open-source. Take care, Jon.

**Comment by lddubeau** [comment]
Thanks for the interest. We do welcome contributions to BTW or any other of our open-source projects. Contributors need to be fairly self-sufficient with the technologies that are not specific to our projects. For instance if someone wants to contribute to BTW, they should know Python, Django, Celery, eXist-db, Selenium, etc. (It is a long list.) 

Unfortunately, we do not have a handy list of things to do for contributors. The open issues you can find on Github right now for the most part require a high degree of BTW-specific knowledge. In fact, BTW is probably the hardest of our projects to get into because it builds on so many other technologies and requires a significant amount of domain-specific knowledge.
